name: student_lab_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.0  # ✅ Update to latest version
  http: ^1.3.0
  csv: ^6.0.0
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pc.png"
  adaptive_icon_foreground: "assets/pc.png"

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
    - assets/fonts/Roboto-Regular.ttf
